import type { Metadata } from "next";
import { Urbanist, Montserrat } from 'next/font/google';
import "../styles/globals.css";
import clsx from "clsx";
import { Providers } from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  weight: ['400', '500', '600', '700'],
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(urbanist.variable, montserrat.variable)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
